# -*- coding: utf-8 -*-
"""20240904.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWJUPucfEJIU5U2Nr0pV2wKHg7M0QbFO
"""

print("Hello word!")



print("집에 보내줘")

print("Hello python")



"""# 새 섹션

##그래프 그리기
"""

import pylab as py

x_deg=py.arange(-180, 180+1,)
x_rad=py.deg2rad(x_deg)
y=py.sin(x_rad)

py.plot(x_deg, y)

py.xlabel('x(deg)')
py.ylabel('sin(x)')
py.grid(True)

"""###부제목"""

